services:
  nginx:
    image: nginx:1.26-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - apptronium
    depends_on:
      - certbot
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/certs:/etc/letsencrypt
      - ./certbot/certs-data:/var/lib/letsencrypt
      - ./nginx/logs:/var/log/nginx

  certbot:
    image: certbot/certbot:v2.11.0
    user: "${UID}:${GID}"
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certs:/etc/letsencrypt
      - ./certs-data:/var/lib/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/certbot --email apptronium@gmail.com --agree-tos --no-eff-email -d apptronium.com --staging --logs-dir /var/log/letsencrypt

networks:
  apptronium:
    driver: bridge
