version: "3"

services:
  etcd:
    image: bitnami/etcd:3.5.14
    container_name: apisix_etcd
    restart: unless-stopped
    volumes:
      - etcd_data:/bitnami/etcd
    environment:
      - ETCD_ENABLE_V2=true
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - "2379:2379"
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - apptronium_net

  apisix:
    image: apache/apisix:3.11.0-debian
    container_name: apisix_gateway
    restart: unless-stopped
    volumes:
      - ./conf/apisix.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      etcd:
        condition: service_healthy
    ports:
      - "9180:9180"
    networks:
      - apptronium_net

  apisix-dashboard:
    image: apache/apisix-dashboard:3.0.1-alpine
    container_name: apisix_dashboard
    restart: unless-stopped
    volumes:
      - ./conf/dashboard.yaml:/usr/local/apisix-dashboard/conf/conf.yaml:ro
    depends_on:
      - etcd
    ports:
      - "9000:9000"
    networks:
      - apptronium_net

volumes:
  etcd_data:
    driver: local

networks:
  apptronium_net:
    external: true