services:
    nginx:
        image: nginx:1.26-alpine
        container_name: nginx_production
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./conf.d:/etc/nginx/conf.d:ro
            - ../shared/www:/var/www/certbot:ro
            - ../shared/certs:/etc/letsencrypt:ro
        networks:
            - apptronium_net

networks:
    apptronium_net:
        external: true
